SET search_path = adm, public, pg_catalog;
DROP TABLE IF EXISTS SL_KOMORKA_ORG CASCADE
;
DROP TABLE IF EXISTS SL_STANOWISKO CASCADE
;

CREATE TABLE SL_KOMORKA_ORG ( 
	ID_KOMORKI_ORG integer NOT NULL,    /* idektyfikator komórki organizacyjnej */
	NAZWA_KOMORKI varchar(300)    /* nazwa komórki organizacyjnej */
)
;
COMMENT ON TABLE SL_KOMORKA_ORG
    IS 'komórki organizacyjne'
;
COMMENT ON COLUMN SL_KOMORKA_ORG.ID_KOMORKI_ORG
    IS 'idektyfikator komórki organizacyjnej'
;
COMMENT ON COLUMN SL_KOMORKA_ORG.NAZWA_KOMORKI
    IS 'nazwa komórki organizacyjnej'
;

CREATE TABLE SL_STANOWISKO ( 
	ID_STANOWISKA integer NOT NULL,    /* idektyfikator stanowiska */
	NAZWA_STANOWISKA varchar(200)    /* nazwa stanowiska */
)
;
COMMENT ON TABLE SL_STANOWISKO
    IS 'wykaz stanowisk'
;
COMMENT ON COLUMN SL_STANOWISKO.ID_STANOWISKA
    IS 'idektyfikator stanowiska'
;
COMMENT ON COLUMN SL_STANOWISKO.NAZWA_STANOWISKA
    IS 'nazwa stanowiska'
;


ALTER TABLE SL_KOMORKA_ORG
	ADD CONSTRAINT UQ_SL_KOMORKA_ORG_ID_KOMORKI_ORG UNIQUE (ID_KOMORKI_ORG)
;
ALTER TABLE SL_STANOWISKO
	ADD CONSTRAINT UQ_SL_STANOWISKO_ID_STANOWISKA UNIQUE (ID_STANOWISKA)
;
ALTER TABLE SL_KOMORKA_ORG ADD CONSTRAINT PK_SL_KOMORKA_ORG 
	PRIMARY KEY (ID_KOMORKI_ORG)
;


ALTER TABLE SL_STANOWISKO ADD CONSTRAINT PK_SL_STANOWISKO 
	PRIMARY KEY (ID_STANOWISKA)
;
